id: P7E18D930
initial_creation_type: input
source_metadata:
  title: Prajñāpāramitā (Deity) Series
  language: en
  description: 'Texts related to the Great Mother (yum chen) Prajñāpāramitā, mother
    of all the buddhas:'
  volume:
    99caefe048e44697b4243af1c0161e6b:
      title: Guru Yoga of the Great Learned and Accomplished Ācārya Haribhadra
      parent: Guru Yoga
    45f6e9577b444373856bba1928227eef:
      title: A Brief Visualization and Recitation of the Great Mother Prajñāpāramitā
      parent: Sādhanas
created_at: '2022-03-01T05:13:22.915855'
last_modified_at: '2022-03-01T05:13:22.915861'
